### ISSUE TITLE
it can't go " if(btn_state == TBN_DOWN) { " switch.

### ISSUE THREAD

**Issue by lbingasd** [liuyanghejerry/Qt-TabletSupport#1]
I have wacom driver and tablet,but it can't go " if(btn_state == TBN_DOWN) { " switch. Can you help me?

**Comment by liuyanghejerry** [comment]
Sorry for your inconvenience. But This project is pretty much obsolete and I don't think I can really help you. Last time I looked at the source is about 3 years ago.

You may want to check out official Qt source code to  get a better understanding of how Qt handle this.

**Comment by lbingasd** [comment]
能加个好友请教一下么？lbingasd@gmail.com 谢谢

**Comment by lbingasd** [comment]
你好能告诉我一个你的联系方式么？想跟你请教一些问题。我的邮箱是lbingasd@gmail.com
